In [31]:
"""
Задание 1
Создайте numpy array с элементами от числа N до 0 
(например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).
"""

import numpy as np

n = int(input())
n_string =[]

while n > 0:
    n -= 1
    n_string.append(n)

nyphy_array = np.array(n_string)
print(nyphy_array, type(nyphy_array))


78
[77 76 75 74 73 72 71 70 69 68 67 66 65 64 63 62 61 60 59 58 57 56 55 54
 53 52 51 50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30
 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6
  5  4  3  2  1  0] <class 'numpy.ndarray'>


In [45]:
"""
Задание 2
Создайте диагональную матрицу с элементами от N до 0. 
Посчитайте сумму ее значений на диагонали.
"""

import numpy as np

n = int(input())
i = 0

diagonal_decreasing_matrix = np.rot90(np.diag(np.arange(n), k=0),2)
    
print (diagonal_decreasing_matrix)
print(sum(diagonal_decreasing_matrix.diagonal()))


9
[[8 0 0 0 0 0 0 0 0]
 [0 7 0 0 0 0 0 0 0]
 [0 0 6 0 0 0 0 0 0]
 [0 0 0 5 0 0 0 0 0]
 [0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0]]
36


In [ ]:
"""
Задание 3
Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. 
Определите какому фильму было выставлено больше всего оценок 5.0.
"""



In [ ]:
"""
Задание 4
По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония)
категорий 4, 12 и 21 за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity.
"""

In [28]:
"""
Задание 5
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3
"""

from numpy import linalg
import numpy as np

a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array([3, 12, -3])

print (linalg.solve(a, b))
np.allclose(np.dot(a, linalg.solve(a, b)), b)

[ 0.2         3.93333333 -5.66666667]


True